//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolabilir. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcheryApp_MVC.Account {
    
    
    public partial class ForgotPassword {
        
        /// <summary>
        /// loginForm denetimi.
        /// </summary>
        /// <remarks>
        ///Otomatik olarak oluşturulan alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder loginForm;
        
        /// <summary>
        /// ErrorMessage denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik olarak oluşturulan alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder ErrorMessage;
        
        /// <summary>
        /// FailureText denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik olarak oluşturulan alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal FailureText;
        
        /// <summary>
        /// Email denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Email;
        
        /// <summary>
        /// DisplayEmail denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder DisplayEmail;
    }
}
