//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturuldu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcheryApp_MVC.Account {
    
    
    public partial class Manage {
        
        /// <summary>
        /// successMessage denetimi.
        /// </summary>
        /// <remarks>
        ///Otomatik olarak oluşturulan alan.
        /// Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder successMessage;
        
        /// <summary>
        /// ChangePassword denetimi.
        /// </summary>
        /// <remarks>
        ///Otomatik olarak oluşturulan alan.
        /// Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink ChangePassword;
        
        /// <summary>
        /// CreatePassword denetimi.
        /// </summary>
        /// <remarks>
        ///Otomatik olarak oluşturulan alan.
        /// Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink CreatePassword;
        
        /// <summary>
        /// PhoneNumber denetimi.
        /// </summary>
        /// <remarks>
        ///Otomatik olarak oluşturulan alan.
        /// Tasarımcı dosyasından arka plan kod dosyasına alan taşıma bildiriminde değişiklik yapmak için.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label PhoneNumber;
    }
}
