//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafından oluşturuldu.
//
//     Bu dosyada yapılan değişiklikler yanlış davranışlara neden olabilir ve
//     kod yeniden oluşturulursa kaybedilir. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcheryApp_MVC.Account {
    
    
    public partial class ManagePassword {
        
        /// <summary>
        /// setPassword denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder setPassword;
        
        /// <summary>
        /// password denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox password;
        
        /// <summary>
        /// confirmPassword denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox confirmPassword;
        
        /// <summary>
        /// changePasswordHolder denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder changePasswordHolder;
        
        /// <summary>
        /// CurrentPasswordLabel denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label CurrentPasswordLabel;
        
        /// <summary>
        /// CurrentPassword denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox CurrentPassword;
        
        /// <summary>
        /// NewPasswordLabel denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label NewPasswordLabel;
        
        /// <summary>
        /// NewPassword denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox NewPassword;
        
        /// <summary>
        /// ConfirmNewPasswordLabel denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ConfirmNewPasswordLabel;
        
        /// <summary>
        /// ConfirmNewPassword denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox ConfirmNewPassword;
    }
}
