//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafından oluşturuldu.
//
//     Bu dosyada yapılan değişiklikler yanlış davranışlara neden olabilir ve
//     kod yeniden oluşturulursa kaybedilir. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcheryApp_MVC.Account {
    
    
    public partial class TwoFactorAuthenticationSignIn {
        
        /// <summary>
        /// sendcode denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder sendcode;
        
        /// <summary>
        /// Providers denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList Providers;
        
        /// <summary>
        /// ProviderSubmit denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ProviderSubmit;
        
        /// <summary>
        /// verifycode denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder verifycode;
        
        /// <summary>
        /// SelectedProvider denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField SelectedProvider;
        
        /// <summary>
        /// ErrorMessage denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder ErrorMessage;
        
        /// <summary>
        /// FailureText denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal FailureText;
        
        /// <summary>
        /// Code denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Code;
        
        /// <summary>
        /// RememberBrowser denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox RememberBrowser;
        
        /// <summary>
        /// CodeSubmit denetimi.
        /// </summary>
        /// <remarks>
        /// Otomatik oluşturulmuş alan.
        /// Değiştirmek için alan bildirimini tasarımcı dosyasından arka plan kod dosyasına taşıyın.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button CodeSubmit;
    }
}
